name: verbes_irreguliers_francais
description: "Les verbes irréguliers français"

publish_to: 'none'

version: 1.3.1+39

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Barre de navigation
  bottom_navy_bar: ^6.1.0

  # Publicité AdMob
  google_mobile_ads: ^6.0.0

  # Stockage des données
  shared_preferences: ^2.5.3

  # Écran d'introduction
  introduction_screen: ^4.0.0
  confirm_dialog: ^1.0.4
  dots_indicator: ^4.0.1

  # Billing
  in_app_purchase: ^3.2.1
  
  google_sign_in: ^7.1.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  provider: ^6.1.4
  firebase_messaging: ^16.0.0
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true
